### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by ideazhao** [phodal/fe#18]
正在拜读《我的职业是前端工程师》这本书，一口气读了几十页，但发现有几处文字的“错误”，可能漏字或者错字，有些还是关键字，对阅读体验有一定影响，可能造成读者的错误理解或理解障碍。
当然，不知道是您的失误还是软件的问题，我知道写这些东西需要很大精力，您很辛苦，不过还是希望能降低出错率来提升体验哈，感谢！

**Comment by phodal** [comment]
@linggan100 对于写的人来说，要觉察出错误其实挺困难的。所以这个项目是完全开源的放在 GitHub 上，为的是大家看到错的地方能帮助指出修改。开源的精神也在于此，依靠社区而不是依靠个体。

**Comment by faydanube** [comment]
希望可以对电子书的配色修改一下。现在感觉对比度太弱了，眼睛好难受=。= 
白底黑字这样都感觉会更舒服一点。。希望采纳。。

**Comment by faydanube** [comment]
主要是目录部分，绿色的字体和暗色的背景配合起来对比度太差了。

**Comment by phodal** [comment]
@faydanube GET 暗色的背景是指？

**Comment by faydanube** [comment]
![default](https://user-images.githubusercontent.com/8817046/53314047-4a87c480-38f7-11e9-8aac-c7727065d53d.png)

看起来很昏暗的感觉，希望目录部分对比度鲜明一些，正文还好。

ps：昨天看了一整天大神的github，然后去做时间管理去了=。=
