### ISSUE TITLE
chapter 08《SEO 优化技巧 ：如何设计一个高质量的 URL 及页面标题》漏写了些什么？

### ISSUE THREAD

**Issue by Kylooe** [phodal/fe#3]
前辈你好！我在看SEO一章的时候发现了一处遗漏，我刚入门思索了半天也没明白这个遗漏的内容到底会是什么……
在chapter-08.md中的36行：

> 检查页面中的

检查页面中的什么呢？

**Comment by phodal** [comment]
@Kylooe 应该是打错了。。想了两天也没想起来是什么。。
