### ISSUE TITLE
null

### ISSUE THREAD

**Issue by ouvens** [phodal/fe#9]
null

**Comment by phodal** [comment]
@ouvens 感觉深度上还是有所不足~~。这是本电子书，是不推荐书的。可以推荐到：https://github.com/phodal/booktree 或者 https://github.com/phodal/growth

**Comment by ouvens** [comment]
主要讲解思维和体系，不讲过多代码技术，因为读者的时间是有限的，主要还是思想～

**Comment by ouvens** [comment]
错误的推广方式

**Comment by justjavac** [comment]
@ouvens 这个 issue 有点不合适吧

**Comment by ouvens** [comment]
justjavac说的很有道理，本只是想宣传下，无心之失～

**Comment by shu4i** [comment]
@ouvens phodal可能自以为它的书更高大上吧，其实是假大空《全栈应用开发-精益实践》
